#!/bin/bash
set -e

echo "Stage 2: Inside debian proot-distro"

# --- Update & upgrade ---
echo "Updating system..."
apt update && apt upgrade -y

# --- Install dependencies ---
echo "Installing required packages..."
apt install -y git nodejs npm chromium openssl curl patch

# --- Clone or update repository ---
REPO_DIR="whatsberry-public"
REPO_URL="https://github.com/danzkigg/whatsberry-public.git"

if [ -d "$REPO_DIR/.git" ]; then
  echo "Repository already exists, updating..."
  cd "$REPO_DIR"
  git fetch --all
  git reset --hard origin/main
else
  echo "Cloning repository..."
  git clone "$REPO_URL"
  cd "$REPO_DIR"
fi

# --- Install Node.js dependencies ---
echo "Installing node dependencies..."
PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true npm install
npm install -g pm2

# --- Generate .env if not exists ---
if [ ! -f .env ]; then
  echo "Creating .env file..."
  API_KEY=$(openssl rand -hex 32)

  cat > .env <<EOF
# This .env file was generated by github.com/RedsonBr140/termux-whatsberry-server.
# Feel free to modify it as you wish.

# Server Port
PORT=3000

# API Key - (Auto generated)
# You can generate one with: openssl rand -hex 32
API_KEY=$API_KEY
EOF

  echo "New API key generated: $API_KEY"
else
  echo ".env file already exists, keeping existing configuration."
  API_KEY=$(grep -E '^API_KEY=' .env | cut -d= -f2- || echo "(unknown)")
fi

# --- Apply patch only if not already applied ---
PATCH_FILE="termux_patch.diff"
PATCH_URL="linktothepatch"

echo "Downloading patch..."
curl -fsSL "$PATCH_URL" -o "$PATCH_FILE"

if git apply --check "$PATCH_FILE" >/dev/null 2>&1; then
  echo "Applying patch..."
  git apply "$PATCH_FILE"
else
  echo "Patch already applied or cannot apply cleanly, skipping."
fi

# --- Start server ---
echo "Starting server with PM2..."
npm run pm2:start || pm2 restart all

echo
echo "✅ Server installation complete!"
echo "🔑 API Key: $API_KEY"
echo "🚀 Directory: $(pwd)"
