#!/bin/bash
set -e

# Define colors and prefixes
RED='\033[0;31m'
GREEN='\033[0;32m'
CYAN='\033[0;36m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

INFO="${CYAN}[INFO]${NC}"
SUCCESS="${GREEN}[SUCCESS]${NC}"
ERROR="${RED}[ERROR]${NC}"

echo -e "${CYAN}[STAGE] Stage 2: Inside Debian proot-distro${NC}"

# --- Update & upgrade ---
echo -e "${INFO} Updating system..."
apt update && apt upgrade -y
echo -e "${SUCCESS} System updated."

# --- Install dependencies ---
echo -e "${INFO} Installing required packages..."
apt install -y git nodejs npm chromium openssl curl patch
echo -e "${SUCCESS} Required packages installed."

# --- Clone or update repository ---
REPO_DIR="whatsberry-public"
REPO_URL="https://github.com/danzkigg/whatsberry-public.git"

if [ -d "$REPO_DIR/.git" ]; then
  echo -e "${INFO} Repository already exists, updating..."
  cd "$REPO_DIR"
  git fetch --all
  git reset --hard origin/main
  echo -e "${SUCCESS} Repository updated."
else
  echo -e "${INFO} Cloning repository..."
  git clone "$REPO_URL"
  cd "$REPO_DIR"
  echo -e "${SUCCESS} Repository cloned."
fi

# --- Install Node.js dependencies ---
echo -e "${INFO} Installing Node.js dependencies..."
PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true npm install
npm install -g pm2
echo -e "${SUCCESS} Node.js dependencies installed."

# --- Generate .env if not exists ---
if [ ! -f .env ]; then
  echo -e "${INFO} Creating .env file..."
  API_KEY=$(openssl rand -hex 32)

  cat > .env <<EOF
# This .env file was generated by github.com/RedsonBr140/termux-whatsberry-server.
# Feel free to modify it as you wish.

# Server Port
PORT=3000

# API Key - (Auto generated)
# You can generate one with: openssl rand -hex 32
API_KEY=$API_KEY
EOF

  echo -e "${SUCCESS} New API key generated: $API_KEY"
else
  echo -e "${INFO} .env file already exists, keeping existing configuration."
  API_KEY=$(grep -E '^API_KEY=' .env | cut -d= -f2- || echo "(unknown)")
fi

# --- Apply patch only if not already applied ---
PATCH_FILE="termux_patch.diff"
PATCH_URL="https://redsonbr140.github.io/termux-whatsberry-installer/patch/termux_patch.diff"

echo -e "${INFO} Downloading patch..."
curl -fsSL "$PATCH_URL" -o "$PATCH_FILE"

if git apply --check "$PATCH_FILE" >/dev/null 2>&1; then
  echo -e "${INFO} Applying patch..."
  git apply "$PATCH_FILE"
  echo -e "${SUCCESS} Patch applied."
else
  echo -e "${INFO} Patch already applied or cannot apply cleanly, skipping."
fi

# --- Start server ---
echo -e "${INFO} Starting server with PM2..."
npm run pm2:start || pm2 restart all
echo -e "${SUCCESS} Server started."

echo
echo -e "${GREEN}✅ Server installation complete!${NC}"
echo -e "${YELLOW}🔑 API Key: $API_KEY${NC}"
echo -e "${YELLOW}🚀 Directory: $(pwd)${NC}"
